// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function GetLCUData() {
  return window['go']['main']['App']['GetLCUData']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveAutoPickSettings(arg1) {
  return window['go']['main']['App']['SaveAutoPickSettings'](arg1);
}

export function ToggleAutoAccept(arg1) {
  return window['go']['main']['App']['ToggleAutoAccept'](arg1);
}
