// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function GetLCUData():Promise<main.LCUResponse>;

export function GetSettings():Promise<config.Settings>;

export function SaveAutoPickSettings(arg1:config.AutoPickSettings):Promise<void>;

export function ToggleAutoAccept(arg1:boolean):Promise<void>;
